<a href="https://colab.research.google.com/github/SinghAbhinav04/podcast-time-prediction/blob/main/podcast_time_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd


In [3]:
X_train= pd.read_csv("/content/train (1).csv")
X_test= pd.read_csv("/content/test (1).csv")
X_train.head()


id     Podcast_Name Episode_Title  Episode_Length_minutes       Genre  \
0   0  Mystery Matters    Episode 98                     NaN  True Crime   
1   1    Joke Junction    Episode 26                  119.80      Comedy   
2   2   Study Sessions    Episode 16                   73.90   Education   
3   3   Digital Digest    Episode 45                   67.17  Technology   
4   4      Mind & Body    Episode 86                  110.51      Health   

   Host_Popularity_percentage Publication_Day Publication_Time  \
0                       74.81        Thursday            Night   
1                       66.95        Saturday        Afternoon   
2                       69.97         Tuesday          Evening   
3                       57.22          Monday          Morning   
4                       80.07          Monday        Afternoon   

   Guest_Popularity_percentage  Number_of_Ads Episode_Sentiment  \
0                          NaN            0.0          Positive   
1                        75.95            2.0          Negative   
2                         8.97            0.0          Negative   
3                        78.70            2.0          Positive   
4                        58.68            3.0           Neutral   

   Listening_Time_minutes  
0                31.41998  
1                88.01241  
2                44.92531  
3                46.27824  
4                75.61031

In [4]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 750000 entries, 0 to 749999
Data columns (total 12 columns):
 #   Column                       Non-Null Count   Dtype  
---  ------                       --------------   -----  
 0   id                           750000 non-null  int64  
 1   Podcast_Name                 750000 non-null  object 
 2   Episode_Title                750000 non-null  object 
 3   Episode_Length_minutes       662907 non-null  float64
 4   Genre                        750000 non-null  object 
 5   Host_Popularity_percentage   750000 non-null  float64
 6   Publication_Day              750000 non-null  object 
 7   Publication_Time             750000 non-null  object 
 8   Guest_Popularity_percentage  603970 non-null  float64
 9   Number_of_Ads                749999 non-null  float64
 10  Episode_Sentiment            750000 non-null  object 
 11  Listening_Time_minutes       750000 non-null  float64
dtypes: float64(5), int64(1), object(6)
memory usage: 68.7+ MB


In [5]:
X_train.loc[X_train["Episode_Length_minutes"].isna()].count()

id                             87093
Podcast_Name                   87093
Episode_Title                  87093
Episode_Length_minutes             0
Genre                          87093
Host_Popularity_percentage     87093
Publication_Day                87093
Publication_Time               87093
Guest_Popularity_percentage    64921
Number_of_Ads                  87093
Episode_Sentiment              87093
Listening_Time_minutes         87093
dtype: int64

In [6]:
X_train[X_train['Podcast_Name']=="Mystery Matters"].loc[X_train['Episode_Length_minutes'].isna()]

id     Podcast_Name Episode_Title  Episode_Length_minutes  \
0            0  Mystery Matters    Episode 98                     NaN   
246        246  Mystery Matters    Episode 45                     NaN   
1085      1085  Mystery Matters    Episode 36                     NaN   
2288      2288  Mystery Matters    Episode 64                     NaN   
2544      2544  Mystery Matters    Episode 47                     NaN   
...        ...              ...           ...                     ...   
748198  748198  Mystery Matters    Episode 49                     NaN   
748832  748832  Mystery Matters    Episode 89                     NaN   
749155  749155  Mystery Matters    Episode 58                     NaN   
749208  749208  Mystery Matters    Episode 84                     NaN   
749868  749868  Mystery Matters    Episode 80                     NaN   

             Genre  Host_Popularity_percentage Publication_Day  \
0       True Crime                       74.81        Thursday   
246     True Crime                       74.92         Tuesday   
1085    True Crime                       41.06          Sunday   
2288    True Crime                       64.54        Saturday   
2544    True Crime                       36.75          Monday   
...            ...                         ...             ...   
748198  True Crime                       67.24       Wednesday   
748832  True Crime                       89.10        Thursday   
749155  True Crime                       72.33        Saturday   
749208  True Crime                       69.99          Monday   
749868  True Crime                       33.15        Thursday   

       Publication_Time  Guest_Popularity_percentage  Number_of_Ads  \
0                 Night                          NaN            0.0   
246           Afternoon                          NaN            2.0   
1085            Morning                        46.03            3.0   
2288              Night                        34.95            3.0   
2544              Night                        84.41            1.0   
...                 ...                          ...            ...   
748198          Morning                        52.91            2.0   
748832          Evening                          NaN            3.0   
749155            Night                        58.07            3.0   
749208            Night                          NaN            1.0   
749868            Night                        27.19            0.0   

       Episode_Sentiment  Listening_Time_minutes  
0               Positive                31.41998  
246              Neutral                62.94347  
1085            Negative                78.27000  
2288             Neutral                12.92198  
2544             Neutral                 4.96483  
...                  ...                     ...  
748198           Neutral                22.72770  
748832           Neutral                21.79187  
749155          Positive                53.28405  
749208           Neutral                76.15661  
749868          Positive                89.95920  

[1818 rows x 12 columns]

In [7]:
X_train.loc[X_train['Guest_Popularity_percentage'].isna()]

id       Podcast_Name Episode_Title  Episode_Length_minutes  \
0            0    Mystery Matters    Episode 98                     NaN   
5            5      Fitness First    Episode 19                   26.54   
8            8       Daily Digest    Episode 32                  105.87   
16          16     Study Sessions    Episode 82                   78.47   
20          20        Funny Folks   Episode 100                   54.67   
...        ...                ...           ...                     ...   
749989  749989      Home & Living    Episode 78                   97.51   
749991  749991  Business Insights     Episode 5                   62.46   
749994  749994         Laugh Line    Episode 67                    8.93   
749995  749995       Learning Lab    Episode 25                   75.66   
749996  749996    Business Briefs    Episode 21                   75.75   

             Genre  Host_Popularity_percentage Publication_Day  \
0       True Crime                       74.81        Thursday   
5           Health                       48.96        Saturday   
8             News                       69.81          Monday   
16       Education                       48.84          Sunday   
20          Comedy                       45.47       Wednesday   
...            ...                         ...             ...   
749989   Lifestyle                       91.92       Wednesday   
749991    Business                       30.03         Tuesday   
749994      Comedy                       85.52        Saturday   
749995   Education                       69.36        Saturday   
749996    Business                       35.21        Saturday   

       Publication_Time  Guest_Popularity_percentage  Number_of_Ads  \
0                 Night                          NaN            0.0   
5             Afternoon                          NaN            3.0   
8               Evening                          NaN            2.0   
16            Afternoon                          NaN            2.0   
20            Afternoon                          NaN            2.0   
...                 ...                          ...            ...   
749989          Evening                          NaN            3.0   
749991        Afternoon                          NaN            0.0   
749994          Evening                          NaN            1.0   
749995          Morning                          NaN            0.0   
749996            Night                          NaN            2.0   

       Episode_Sentiment  Listening_Time_minutes  
0               Positive                31.41998  
5               Positive                22.77047  
8                Neutral                68.00124  
16               Neutral                42.89441  
20               Neutral                29.22750  
...                  ...                     ...  
749989           Neutral                56.44464  
749991          Positive                53.32434  
749994           Neutral                 7.39878  
749995          Negative                56.87058  
749996           Neutral                45.46242  

[146030 rows x 12 columns]

In [8]:
X_train.loc[X_train['Number_of_Ads'].isna()]

id Podcast_Name Episode_Title  Episode_Length_minutes   Genre  \
247170  247170     Game Day    Episode 33                   35.66  Sports   

        Host_Popularity_percentage Publication_Day Publication_Time  \
247170                       27.35          Friday          Evening   

        Guest_Popularity_percentage  Number_of_Ads Episode_Sentiment  \
247170                        49.87            NaN          Negative   

        Listening_Time_minutes  
247170                23.94516

In [9]:
X_train.loc[X_train['Podcast_Name']=="Game Day"]

id Podcast_Name Episode_Title  Episode_Length_minutes   Genre  \
12          12     Game Day    Episode 76                   82.14  Sports   
41          41     Game Day     Episode 4                   33.02  Sports   
44          44     Game Day    Episode 24                  111.15  Sports   
181        181     Game Day    Episode 15                   45.95  Sports   
208        208     Game Day    Episode 97                     NaN  Sports   
...        ...          ...           ...                     ...     ...   
749871  749871     Game Day    Episode 49                   77.06  Sports   
749912  749912     Game Day    Episode 48                    6.60  Sports   
749927  749927     Game Day     Episode 8                  105.44  Sports   
749939  749939     Game Day    Episode 84                   13.04  Sports   
749984  749984     Game Day    Episode 13                     NaN  Sports   

        Host_Popularity_percentage Publication_Day Publication_Time  \
12                           86.65        Saturday          Morning   
41                           27.78       Wednesday          Morning   
44                           53.98        Saturday          Evening   
181                          89.15          Sunday          Evening   
208                          52.75       Wednesday        Afternoon   
...                            ...             ...              ...   
749871                       72.33          Sunday        Afternoon   
749912                       67.14          Sunday          Morning   
749927                       56.15        Thursday          Evening   
749939                       51.69       Wednesday          Morning   
749984                       70.22         Tuesday          Evening   

        Guest_Popularity_percentage  Number_of_Ads Episode_Sentiment  \
12                            35.19            1.0           Neutral   
41                            91.13            2.0          Positive   
44                            34.96            1.0          Positive   
181                             NaN            2.0           Neutral   
208                             NaN            0.0           Neutral   
...                             ...            ...               ...   
749871                          NaN            2.0          Positive   
749912                          NaN            0.0          Negative   
749927                          NaN            2.0          Positive   
749939                        45.40            1.0           Neutral   
749984                        53.74            1.0          Positive   

        Listening_Time_minutes  
12                    48.26043  
41                    16.36000  
44                    97.16370  
181                   39.98581  
208                   33.51215  
...                        ...  
749871                62.17661  
749912                 0.00000  
749927                70.95354  
749939                 8.48000  
749984                37.26790  

[19272 rows x 12 columns]

# Plan for handling the null values

1)**find the name of the podcast and then avg it and  inplace of null replace it**

In [10]:
def handle_null_val():
  for podcast in X_train['Podcast_Name'].unique():
    sum = X_train.loc[X_train['Podcast_Name']==podcast]['Episode_Length_minutes'].sum()
    count = X_train.loc[X_train['Podcast_Name']==podcast]['Episode_Length_minutes'].count()
    avg = sum/count
    X_train.loc[X_train['Podcast_Name']==podcast,'Episode_Length_minutes']=X_train.loc[X_train['Podcast_Name']==podcast,'Episode_Length_minutes'].fillna(avg)


In [11]:
handle_null_val()

In [12]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 750000 entries, 0 to 749999
Data columns (total 12 columns):
 #   Column                       Non-Null Count   Dtype  
---  ------                       --------------   -----  
 0   id                           750000 non-null  int64  
 1   Podcast_Name                 750000 non-null  object 
 2   Episode_Title                750000 non-null  object 
 3   Episode_Length_minutes       750000 non-null  float64
 4   Genre                        750000 non-null  object 
 5   Host_Popularity_percentage   750000 non-null  float64
 6   Publication_Day              750000 non-null  object 
 7   Publication_Time             750000 non-null  object 
 8   Guest_Popularity_percentage  603970 non-null  float64
 9   Number_of_Ads                749999 non-null  float64
 10  Episode_Sentiment            750000 non-null  object 
 11  Listening_Time_minutes       750000 non-null  float64
dtypes: float64(5), int64(1), object(6)
memory usage: 68.7+ MB


In [13]:
def handle_null_val_2():
  for podcast in X_train['Podcast_Name'].unique():
    sum = X_train.loc[X_train['Podcast_Name']==podcast]['Guest_Popularity_percentage'].sum()
    count = X_train.loc[X_train['Podcast_Name']==podcast]['Guest_Popularity_percentage'].count()
    avg = sum/count
    X_train.loc[X_train['Podcast_Name']==podcast,'Guest_Popularity_percentage']=X_train.loc[X_train['Podcast_Name']==podcast,'Guest_Popularity_percentage'].fillna(avg)

In [14]:
handle_null_val_2()

In [15]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 750000 entries, 0 to 749999
Data columns (total 12 columns):
 #   Column                       Non-Null Count   Dtype  
---  ------                       --------------   -----  
 0   id                           750000 non-null  int64  
 1   Podcast_Name                 750000 non-null  object 
 2   Episode_Title                750000 non-null  object 
 3   Episode_Length_minutes       750000 non-null  float64
 4   Genre                        750000 non-null  object 
 5   Host_Popularity_percentage   750000 non-null  float64
 6   Publication_Day              750000 non-null  object 
 7   Publication_Time             750000 non-null  object 
 8   Guest_Popularity_percentage  750000 non-null  float64
 9   Number_of_Ads                749999 non-null  float64
 10  Episode_Sentiment            750000 non-null  object 
 11  Listening_Time_minutes       750000 non-null  float64
dtypes: float64(5), int64(1), object(6)
memory usage: 68.7+ MB


In [16]:
X_train.loc[X_train['Number_of_Ads'].isna()]

id Podcast_Name Episode_Title  Episode_Length_minutes   Genre  \
247170  247170     Game Day    Episode 33                   35.66  Sports   

        Host_Popularity_percentage Publication_Day Publication_Time  \
247170                       27.35          Friday          Evening   

        Guest_Popularity_percentage  Number_of_Ads Episode_Sentiment  \
247170                        49.87            NaN          Negative   

        Listening_Time_minutes  
247170                23.94516

In [17]:
sum = X_train.loc[X_train['Podcast_Name']=="Game Day"]['Number_of_Ads'].sum()
count = X_train.loc[X_train['Podcast_Name']=="Game Day"]['Number_of_Ads'].count()
avg = sum/count
X_train.loc[X_train['Podcast_Name']=="Game Day", "Number_of_Ads"]=X_train.loc[X_train['Podcast_Name']=="Game Day","Number_of_Ads"].fillna(avg)

In [18]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 750000 entries, 0 to 749999
Data columns (total 12 columns):
 #   Column                       Non-Null Count   Dtype  
---  ------                       --------------   -----  
 0   id                           750000 non-null  int64  
 1   Podcast_Name                 750000 non-null  object 
 2   Episode_Title                750000 non-null  object 
 3   Episode_Length_minutes       750000 non-null  float64
 4   Genre                        750000 non-null  object 
 5   Host_Popularity_percentage   750000 non-null  float64
 6   Publication_Day              750000 non-null  object 
 7   Publication_Time             750000 non-null  object 
 8   Guest_Popularity_percentage  750000 non-null  float64
 9   Number_of_Ads                750000 non-null  float64
 10  Episode_Sentiment            750000 non-null  object 
 11  Listening_Time_minutes       750000 non-null  float64
dtypes: float64(5), int64(1), object(6)
memory usage: 68.7+ MB


In [19]:
id = X_test.drop(columns=["id"],inplace=True)

In [20]:
def handle_null_val_test():
  for podcast in X_test['Podcast_Name'].unique():
    sum = X_test.loc[X_test['Podcast_Name']==podcast]['Episode_Length_minutes'].sum()
    count = X_test.loc[X_test['Podcast_Name']==podcast]['Episode_Length_minutes'].count()
    avg = sum/count
    X_test.loc[X_test['Podcast_Name']==podcast,'Episode_Length_minutes']=X_test.loc[X_test['Podcast_Name']==podcast,'Episode_Length_minutes'].fillna(avg)


In [21]:
handle_null_val_test()

In [22]:
def handle_null_val_test_2():
  for podcast in X_test['Podcast_Name'].unique():
    sum = X_test.loc[X_test['Podcast_Name']==podcast]['Guest_Popularity_percentage'].sum()
    count = X_test.loc[X_test['Podcast_Name']==podcast]['Guest_Popularity_percentage'].count()
    avg = sum/count
    X_test.loc[X_test['Podcast_Name']==podcast,'Guest_Popularity_percentage']=X_test.loc[X_test['Podcast_Name']==podcast,'Guest_Popularity_percentage'].fillna(avg)

In [23]:
handle_null_val_test_2()

In [24]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column                       Non-Null Count   Dtype  
---  ------                       --------------   -----  
 0   Podcast_Name                 250000 non-null  object 
 1   Episode_Title                250000 non-null  object 
 2   Episode_Length_minutes       250000 non-null  float64
 3   Genre                        250000 non-null  object 
 4   Host_Popularity_percentage   250000 non-null  float64
 5   Publication_Day              250000 non-null  object 
 6   Publication_Time             250000 non-null  object 
 7   Guest_Popularity_percentage  250000 non-null  float64
 8   Number_of_Ads                250000 non-null  float64
 9   Episode_Sentiment            250000 non-null  object 
dtypes: float64(4), object(6)
memory usage: 19.1+ MB


#Encoding Strategy

1)Label Encoder

2)One Hot Encoding



In [25]:
from sklearn.preprocessing import LabelEncoder , OneHotEncoder


In [26]:
#label encoding for all obj ft except sentiment
label_encoder=LabelEncoder()
for col in X_train.columns:
  if X_train[col].dtype=="object" and col!="Episode_Sentiment":
    X_train[col]=label_encoder.fit_transform(X_train[col])
    X_test[col]=label_encoder.transform(X_test[col])

In [27]:
X_train["Episode_Sentiment"]=label_encoder.fit_transform(X_train['Episode_Sentiment'])
X_test["Episode_Sentiment"]=label_encoder.transform(X_test['Episode_Sentiment'])

In [28]:
X_train.head()

id  Podcast_Name  Episode_Title  Episode_Length_minutes  Genre  \
0   0            34             98               64.388461      9   
1   1            24             19              119.800000      1   
2   2            40              8               73.900000      2   
3   3            10             40               67.170000      8   
4   4            31             85              110.510000      3   

   Host_Popularity_percentage  Publication_Day  Publication_Time  \
0                       74.81                4                 3   
1                       66.95                2                 0   
2                       69.97                5                 1   
3                       57.22                1                 2   
4                       80.07                1                 0   

   Guest_Popularity_percentage  Number_of_Ads  Episode_Sentiment  \
0                    52.241037            0.0                  2   
1                    75.950000            2.0                  0   
2                     8.970000            0.0                  0   
3                    78.700000            2.0                  2   
4                    58.680000            3.0                  1   

   Listening_Time_minutes  
0                31.41998  
1                88.01241  
2                44.92531  
3                46.27824  
4                75.61031

In [29]:
y_train = X_train["Listening_Time_minutes"]
X_train.drop(columns=["id", "Listening_Time_minutes"],inplace=True)

In [30]:
X_train.head()

Podcast_Name  Episode_Title  Episode_Length_minutes  Genre  \
0            34             98               64.388461      9   
1            24             19              119.800000      1   
2            40              8               73.900000      2   
3            10             40               67.170000      8   
4            31             85              110.510000      3   

   Host_Popularity_percentage  Publication_Day  Publication_Time  \
0                       74.81                4                 3   
1                       66.95                2                 0   
2                       69.97                5                 1   
3                       57.22                1                 2   
4                       80.07                1                 0   

   Guest_Popularity_percentage  Number_of_Ads  Episode_Sentiment  
0                    52.241037            0.0                  2  
1                    75.950000            2.0                  0  
2                     8.970000            0.0                  0  
3                    78.700000            2.0                  2  
4                    58.680000            3.0                  1

## SVR , DecisionTree , Ridge , Lasso

In [31]:
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import Ridge , Lasso

In [32]:
#SVR
'''svr = SVR(kernel="rbf", gamma="scale", C=1.0 , verbose=True)
svr.fit(X_train, y_train)'''

'svr = SVR(kernel="rbf", gamma="scale", C=1.0 , verbose=True)\nsvr.fit(X_train, y_train)'

In [33]:
#DTR
dtr = DecisionTreeRegressor(max_depth=5)
dtr.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=5)

In [34]:
#Ridge
ridge_regression = Ridge(alpha=1.0)
ridge_regression.fit(X_train, y_train)

Ridge()

In [35]:
#Lasso
laso_regression = Lasso(alpha=1.0)
laso_regression.fit(X_train, y_train)

Lasso()

##Same work for test set -> first handle all null values and then label encode them and then do the prediction part

In [36]:
X_test.head()

Podcast_Name  Episode_Title  Episode_Length_minutes  Genre  \
0            11             71                   78.96      2   
1            36             16                   27.87      5   
2            24              3                   69.10      1   
3             4             71                  115.39      1   
4            27             46                   72.32      4   

   Host_Popularity_percentage  Publication_Day  Publication_Time  \
0                       38.11                2                 1   
1                       71.29                3                 2   
2                       67.89                0                 1   
3                       23.40                3                 2   
4                       58.10                6                 2   

   Guest_Popularity_percentage  Number_of_Ads  Episode_Sentiment  
0                    53.330000            1.0                  1  
1                    51.985752            0.0                  1  
2                    97.510000            0.0                  2  
3                    51.750000            2.0                  2  
4                    11.300000            2.0                  1

In [37]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column                       Non-Null Count   Dtype  
---  ------                       --------------   -----  
 0   Podcast_Name                 250000 non-null  int64  
 1   Episode_Title                250000 non-null  int64  
 2   Episode_Length_minutes       250000 non-null  float64
 3   Genre                        250000 non-null  int64  
 4   Host_Popularity_percentage   250000 non-null  float64
 5   Publication_Day              250000 non-null  int64  
 6   Publication_Time             250000 non-null  int64  
 7   Guest_Popularity_percentage  250000 non-null  float64
 8   Number_of_Ads                250000 non-null  float64
 9   Episode_Sentiment            250000 non-null  int64  
dtypes: float64(4), int64(6)
memory usage: 19.1 MB


In [38]:
dtr_pred = dtr.predict(X_test)
lasso_pred = laso_regression.predict(X_test)
ridge_pred = ridge_regression.predict(X_test)

In [39]:
dtr_pred

array([58.30423221, 16.22976271, 44.45256993, ...,  6.06884292,
       77.3323873 , 58.30423221])

In [40]:
lasso_pred

array([55.86742607, 19.58156293, 50.32105345, ...,  4.88609788,
       79.97276785, 56.36383946])

In [41]:
ridge_pred

array([55.92968311, 20.69584296, 51.67684456, ...,  4.84734397,
       79.11841261, 56.82284976])

#Hyperparam tuning + RandomizedSearchCV

In [42]:
from sklearn.model_selection import RandomizedSearchCV

In [43]:
rand_params={
    "max_depth":[5,8,10],
    "min_samples_split":[5,7,9],
    "criterion":["squared_error"],
    "min_samples_leaf":[5,8,10],
}

In [44]:
random_search = RandomizedSearchCV(
    estimator=dtr,
    param_distributions=rand_params,
    n_iter=5,
    cv=5,
    verbose=2,
    n_jobs=-1
)
random_search.fit(X_train, y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits


RandomizedSearchCV(cv=5, estimator=DecisionTreeRegressor(max_depth=5), n_iter=5,
                   n_jobs=-1,
                   param_distributions={'criterion': ['squared_error'],
                                        'max_depth': [5, 8, 10],
                                        'min_samples_leaf': [5, 8, 10],
                                        'min_samples_split': [5, 7, 9]},
                   verbose=2)

In [45]:
best_params = random_search.best_params_
best_params

{'min_samples_split': 5,
 'min_samples_leaf': 5,
 'max_depth': 8,
 'criterion': 'squared_error'}

In [46]:
best_model = random_search.best_estimator_
best_model

DecisionTreeRegressor(max_depth=8, min_samples_leaf=5, min_samples_split=5)

In [47]:
final_pred = best_model.predict(X_test)
final_pred

array([56.16868398, 17.55481788, 49.76166583, ...,  7.41491208,
       72.52673689, 57.49311524])

In [48]:
sample = pd.read_csv("/content/sample_submission.csv")
sample.head()

id  Listening_Time_minutes
0  750000                  45.437
1  750001                  45.437
2  750002                  45.437
3  750003                  45.437
4  750004                  45.437

In [49]:
num = 750000
submission = pd.DataFrame(columns=["id","Listening_Time_minutes"])
submission["id"]=range(num,num+len(final_pred))
submission["Listening_Time_minutes"]=final_pred
submission.head()

id  Listening_Time_minutes
0  750000               56.168684
1  750001               17.554818
2  750002               49.761666
3  750003               81.119346
4  750004               48.969132

In [50]:
submission.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 2 columns):
 #   Column                  Non-Null Count   Dtype  
---  ------                  --------------   -----  
 0   id                      250000 non-null  int64  
 1   Listening_Time_minutes  250000 non-null  float64
dtypes: float64(1), int64(1)
memory usage: 3.8 MB


In [51]:
submission.to_csv("submission.csv",index=False)

In [52]:
sum = submission["Listening_Time_minutes"].sum()
count = submission["Listening_Time_minutes"].count()
avg = sum/count
avg

np.float64(45.566853166184586)

In [53]:
sum = y_train.sum()
count = y_train.count()
avg = sum/count
avg

np.float64(45.43740628813335)

#Random Forest , XGBOOST , MLPR

In [54]:
from sklearn.ensemble import RandomForestRegressor
import xgboost as xgb

In [55]:
from sklearn.neural_network import MLPRegressor

In [63]:
rfr = RandomForestRegressor(n_estimators=100, max_depth=10, random_state=42)
rfr.fit(X_train, y_train)
rfr_preds = rfr.predict(X_test)
rfr_preds

array([56.63217402, 17.85788429, 49.45549262, ...,  7.4430534 ,
       73.50126422, 57.23384088])

In [57]:
xgbr = xgb.XGBRegressor(n_estimators=100, max_depth=6, learning_rate=0.1, random_state=42)
xgbr.fit(X_train, y_train)
xgbr_preds = xgbr.predict(X_test)
xgbr_preds

array([55.84936  , 18.111692 , 49.016342 , ...,  7.0547085, 74.13454  ,
       57.27973  ], dtype=float32)

In [58]:
mlpr = MLPRegressor(
        hidden_layer_sizes=(128, 64),
        activation='relu',
        solver='adam',
        alpha=0.001,
        learning_rate='adaptive',
        learning_rate_init=0.01,
        max_iter=500,
        early_stopping=True,
        random_state=42
    )
mlpr.fit(X_train , y_train)
mlpr_preds = mlpr.predict(X_test)
mlpr_preds

array([55.58270781, 18.45061548, 52.22673387, ...,  6.66547831,
       76.82784978, 57.4826466 ])

In [59]:
num = 750000
submission = pd.DataFrame(columns=["id","Listening_Time_minutes"])
submission["id"]=range(num,num+len(mlpr_preds))
submission["Listening_Time_minutes"]=mlpr_preds
submission.head()

id  Listening_Time_minutes
0  750000               55.582708
1  750001               18.450615
2  750002               52.226734
3  750003               81.849648
4  750004               49.198430

In [60]:
submission.to_csv("mlpr_submission.csv",index=False)

In [61]:
num = 750000
submission = pd.DataFrame(columns=["id","Listening_Time_minutes"])
submission["id"]=range(num,num+len(xgbr_preds))
submission["Listening_Time_minutes"]=xgbr_preds
submission.head()

id  Listening_Time_minutes
0  750000               55.849361
1  750001               18.111692
2  750002               49.016342
3  750003               80.450333
4  750004               49.101414

In [64]:
submission.to_csv("xgbr_submission.csv",index=False)

#XGB and DTR were the best ones currently

hyperparam tune xgbr and dtr